# Generated by Django 4.2.8 on 2024-01-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_user_gender_alter_user_profil_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('AGRIPRENEUR', 'AGRIPRENEUR'), ('MERCHANT', 'MERCHANT'), ('CLIENT', 'CLIENT'), ('USER', 'USER')], max_length=255, null=True, verbose_name='sexe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profil_type',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='USER', max_length=255, verbose_name='profil type'),
        ),
    ]
