# Generated by Django 4.2.8 on 2024-01-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_user_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sexe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profil_type',
            field=models.CharField(default='USER', max_length=255, verbose_name='profil type'),
        ),
    ]
